# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('vericode', models.CharField(max_length=100)),
                ('verified', models.IntegerField()),
            ],
        ),
    ]
