# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
