# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170205_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Account',
            new_name='User',
        ),
    ]
