# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmarket', '0003_classifierspre_modelfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifierspre',
            name='classifierp',
        ),
    ]
