# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userclassifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierData',
            fields=[
                ('classifierid', models.AutoField(primary_key=True, serialize=False)),
                ('classifierp', models.CharField(max_length=100)),
                ('classifier', models.CharField(max_length=100)),
                ('user', models.IntegerField()),
                ('inputset', models.CharField(max_length=25000)),
                ('outputset', models.CharField(max_length=1500)),
                ('lasttrained', models.DateTimeField(default=False)),
            ],
        ),
    ]
