# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0002_classifierdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifierdata',
            name='type',
            field=models.CharField(default='use', max_length=10),
            preserve_default=False,
        ),
    ]
