# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0002_auto_20170206_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifierdata',
            name='id',
        ),
        migrations.AddField(
            model_name='classifierdata',
            name='classifierid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classifierdata',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
