# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0003_auto_20170206_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifierdata',
            name='inputset',
            field=models.CharField(default=0, max_length=25000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classifierdata',
            name='outputset',
            field=models.CharField(default=0, max_length=1500),
            preserve_default=False,
        ),
    ]
