# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0003_classifierdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifierdata',
            name='lasttrained',
            field=models.DateTimeField(blank=True, default=False),
        ),
    ]
