# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0004_auto_20170206_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifierdata',
            name='database',
        ),
        migrations.AddField(
            model_name='classifierdata',
            name='classifierp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
