# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0004_auto_20170215_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifierdata',
            name='lasttrained',
        ),
    ]
