# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclassifier', '0005_remove_classifierdata_lasttrained'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifierdata',
            name='name',
            field=models.CharField(default='Cool CLassifier', max_length=500),
            preserve_default=False,
        ),
    ]
